# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_q0HxI4xdpENe9oyuJUOi5AsoIq_I92w
"""

class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        i,j = 0, 0
        l = len(nums)
        for j in range(l):
            if nums[j] != nums[i]:
                i += 1
                nums[i] = nums[j]
        return i + 1