# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ieF6GACKWv-zyqsU0lZir3Vk-xENIl0C
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def inorderTraversal(self, root: TreeNode) -> List[int]:
        p = []
        if root is None:
            return p
        return self.inorderTraversal(root.left) + [root.val] + self.inorderTraversal(root.right)